### PR TITLE
[S] LP: setup react skeleton and files for login page and components

### PR DESCRIPTION
**Pull request by jose-m-f**
This PR contains the work required to close ticket [https://trello.com/c/ibAk9Vok](https://trello.com/c/ibAk9Vok)

### CODE REVIEW

**Review by bzw24 — APPROVED** [review]
Looks good, basic set up for react components

**Review by stevkim — CHANGES_REQUESTED** [review]
Everything looks great, but you don't need to import React from every file.

-- You only need to import hooks from react

**Comment by jose-m-f** [comment]
> Everything looks great, but you don't need to import React from every file.
> 
> -- You only need to import hooks from react

I just push the required changes

**Review by stevkim — APPROVED** [review]
Great! Thank you for taking out the React imports

**Pull request merged**
