### PR TITLE
Style scanner

### PR DESCRIPTION
**Pull request by kssampson**
- Used getElementById and classList attributes to manipulate the elements
- UX should flow a bit better, with more naming conventions and buttons instead of text

### CODE REVIEW

**Comment by kssampson** [comment]
@bzw24 I appreciate your attentiveness and running through this feature with the team and making the ask. Let me know if any other changes pop out to you

**Comment by kssampson** [comment]
Trying to scan now, this might be causing a bug. I think it may have to do with the ValetReservaiton page pulling the garage id, or it's a routing issue from the scanner.

**Comment by kssampson** [comment]
Screenshot 2024-01-04 at 9 42 28 PM

**Review by bzw24 — COMMENTED** [review]
I see, so it seems like that scanner mechanism derived from the Html5QrcodeScanner library, which may make it very difficult to style, since it is coming from a 3rd party library. In that case, if styling that component is causing any unintended bug, it'll be okay to leave it as is. However, I do think your implementation of trying to find the html element and adding styling once it is found is a clever way to implement styling on a 3rd party  component.

**Comment by kssampson** [comment]
@bzw24 it was a routing issue 
Screenshot 2024-01-05 at 8 18 58 AM
Got it working again.

**Review by bzw24 — APPROVED** [review]
Good catch, thank you for taking the time to investigate

**Review by kjmak14 — APPROVED** [review]
Cool that you got the styling to work

**Pull request merged**
